# ML Pipeline



1.   data collection / acquire
2.   cleaning / preprocessing => (Data is not clean / is impure)
  *   missing
  *   duplicate  
  *   outliers
3. visualization
4. train-test split
5. train
6. test / predict
7. accuracy / score

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv('/content/homeprices2.csv')
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [5]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets/homeprices2.csv')
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

### Handling Missing Values
1. dropna
2. fillna

measure of central tendancy
- mean
- median
- mode

In [7]:
df.isna()

    area  bedrooms    age  price
0  False     False  False  False
1  False     False  False  False
2  False      True  False  False
3  False     False  False  False
4  False     False  False  False
5  False     False  False  False

In [8]:
df.isna().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [9]:
median_bedrooms = df['bedrooms'].median()
median_bedrooms

4.0

In [10]:
df['bedrooms'] = df['bedrooms'].fillna(median_bedrooms)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
df.isna().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [ ]:
# df.dropna()